<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🔔Alerts | FarmForecast</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="alert.css">
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>

<body>
    <div class="back-btn-container">
        <a href="{{ route('home') }}?explore=true" class="back-btn" title="Back to Home">
            <i class="fas fa-arrow-left"></i>
        </a>
    </div>

    <style>
        .back-btn-container {
            position: fixed;
            top: 25px;
            left: 25px;
            z-index: 9999;
        }

        .back-btn {
            display: flex;
            align-items: center;
            justify-content: center;
            width: 50px;
            height: 50px;
            background-color: white;
            color: var(--primary);
            border-radius: 50%;
            text-decoration: none;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
            transition: all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
            font-size: 1.3rem;
            border: 2px solid var(--primary);
        }

        .back-btn:hover {
            background-color: var(--primary);
            color: white;
            transform: scale(1.15) rotate(-10deg);
            box-shadow: 0 6px 20px rgba(27, 94, 32, 0.3);
        }
    </style>

    <header>
        <h1>Smart Agricultural Dashboard</h1>
        <p>Premium real-time insights for your farming operations</p>
    </header>

    <div class="container">
        <div class="dashboard">
            <!-- Left Column -->
            <div>
                <div class="panel" style="position: relative; z-index: 2;">
                    <h2 class="panel-title">
                        Current Conditions
                        <div id="notification-bell">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round">
                                <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path>
                                <path d="M13.73 21a2 2 0 0 1-3.46 0"></path>
                            </svg>
                            <div class="notification-badge">3</div>
                        </div>
                    </h2>

                    <div class="weather-card">
                        <div style="font-size: 28px; font-weight: 600; font-family: 'Outfit', sans-serif;" id="display-location">{{ $farmProfile->location ?? 'Punjab, Phagwara' }}</div>
                        <div style="font-size: 14px; margin-top: 5px; color: var(--text-muted); font-weight: 500;">
                            <i class="fas fa-vector-square" style="color: var(--success);"></i> <span id="display-field-size">{{ $farmProfile->field_size ?? '120 acres' }}</span>
                            <span style="margin: 0 10px;">|</span>
                            <i class="far fa-calendar-alt" style="color: var(--success);"></i> <span id="current-date">Wednesday, April 16, 2025</span>
                        </div>
                        <div class="temperature" id="current-temp">72°F</div>
                        <div style="font-size: 1.1rem; font-weight: 500; color: var(--text-main);">Partly Cloudy</div>

                        <div class="weather-details">
                            <div class="weather-detail">
                                <div class="detail-value" id="current-humidity">45%</div>
                                <div class="detail-label">Humidity</div>
                            </div>
                            <div class="weather-detail">
                                <div class="detail-value" id="current-precipitation">0%</div>
                                <div class="detail-label">Precipitation</div>
                            </div>
                            <div class="weather-detail">
                                <div class="detail-value" id="current-wind">8 mph</div>
                                <div class="detail-label">Wind</div>
                            </div>
                        </div>
                    </div>

                    <h3 style="margin: 25px 0 15px 0; font-weight: 600;">5-Day Forecast</h3>
                    <div class="forecast-days" id="forecast-container">
                        <!-- Forecast days will be generated by JavaScript -->
                    </div>
                </div>

                <div class="panel">
                    <h2 class="panel-title">Farm Profile</h2>
                    <div class="form-group">
                        <label for="location"><i class="fas fa-map-marker-alt" style="margin-right: 5px; color: var(--primary);"></i> Location</label>
                        <input type="text" id="location" value="{{ $farmProfile->location ?? 'Sacramento Valley, CA' }}">
                    </div>
                    <div class="form-group">
                        <label for="field-size"><i class="fas fa-expand-arrows-alt" style="margin-right: 5px; color: var(--primary);"></i> Field Size (Acres)</label>
                        <input type="text" id="field-size" value="{{ $farmProfile->field_size ?? '120' }}">
                    </div>
                    <div class="form-group">
                        <label for="crop-type"><i class="fas fa-seedling" style="margin-right: 5px; color: var(--primary);"></i> Primary Crop</label>
                        <select id="crop-type">
                            <option value="corn" {{ strtolower($farmProfile->primary_crop ?? '') == 'corn' ? 'selected' : '' }}>Corn</option>
                            <option value="wheat" {{ strtolower($farmProfile->primary_crop ?? '') == 'wheat' ? 'selected' : '' }}>Wheat</option>
                            <option value="soybean" {{ strtolower($farmProfile->primary_crop ?? '') == 'soybean' ? 'selected' : '' }}>Soybean</option>
                            <option value="rice" {{ strtolower($farmProfile->primary_crop ?? '') == 'rice' ? 'selected' : '' }}>Rice</option>
                            <option value="alfalfa" {{ strtolower($farmProfile->primary_crop ?? '') == 'alfalfa' ? 'selected' : '' }}>Alfalfa</option>
                            <option value="tomatoes" {{ strtolower($farmProfile->primary_crop ?? '') == 'tomatoes' ? 'selected' : '' }}>Tomatoes</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="soil-type"><i class="fas fa-layer-group" style="margin-right: 5px; color: var(--primary);"></i> Soil Type</label>
                        <select id="soil-type">
                            <option value="loam" {{ strtolower($farmProfile->soil_type ?? '') == 'loam' ? 'selected' : '' }}>Loam</option>
                            <option value="clay" {{ strtolower($farmProfile->soil_type ?? '') == 'clay' ? 'selected' : '' }}>Clay</option>
                            <option value="sandy" {{ strtolower($farmProfile->soil_type ?? '') == 'sandy' ? 'selected' : '' }}>Sandy</option>
                            <option value="silt" {{ strtolower($farmProfile->soil_type ?? '') == 'silt' ? 'selected' : '' }}>Silt</option>
                            <option value="clay-loam" {{ strtolower($farmProfile->soil_type ?? '') == 'clay-loam' ? 'selected' : '' }}>Clay Loam</option>
                        </select>
                    </div>

                    <button id="update-profile-btn"><i class="fas fa-save" style="margin-right: 8px;"></i> Update Profile</button>
                </div>

                <div class="panel">
                    <h2 class="panel-title"><i class="fas fa-tasks" style="color: var(--primary); margin-right: 10px;"></i> Daily Farm To-Do List</h2>
                    <div class="todo-input-group">
                        <input type="text" id="new-todo-input" placeholder="What needs to be done today?">
                        <button id="add-todo-btn"><i class="fas fa-plus"></i></button>
                    </div>
                    <ul class="todo-list" id="todo-list">
                        @if(isset($todos) && count($todos) > 0)
                        @foreach($todos as $todo)
                        <li class="todo-item {{ $todo->is_completed ? 'completed' : '' }}" data-id="{{ $todo->id }}">
                            <input type="checkbox" class="todo-checkbox" {{ $todo->is_completed ? 'checked' : '' }}>
                            <span class="todo-text">{{ $todo->task }}</span>
                        </li>
                        @endforeach
                        @else
                        <li style="text-align: center; color: var(--text-muted); font-style: italic; padding: 10px;">No tasks for today. Add one above!</li>
                        @endif
                    </ul>
                </div>
            </div>

            <!-- Right Column -->
            <div>
                <!-- Today's Insights -->
                <div class="panel" style="background: linear-gradient(135deg, rgba(255,255,255,0.9), rgba(224,242,241,0.8));">
                    <h2 class="panel-title"><i class="fas fa-chart-line" style="color: var(--primary); margin-right: 10px;"></i> Today's Field Insights</h2>

                    <div class="widget-grid" style="margin-bottom: 20px;">
                        <div class="widget">
                            <div class="widget-icon"><i class="fas fa-users" style="color: #1976d2;"></i></div>
                            <div class="widget-value" id="farmer-count">12</div>
                            <div class="widget-label">Farmers on Field</div>
                        </div>
                        <div class="widget">
                            <div class="widget-icon"><i class="fas fa-tint" style="color: #0288d1;"></i></div>
                            <div class="widget-value" id="water-invested">4,500 L</div>
                            <div class="widget-label">Water Invested Today</div>
                        </div>
                        <div class="widget">
                            <div class="widget-icon"><i class="fas fa-plug" style="color: #f57c00;"></i></div>
                            <div class="widget-value" id="motor-runtime">4.5 hrs</div>
                            <div class="widget-label">Motor Run Time</div>
                        </div>
                        <div class="widget">
                            <div class="widget-icon"><i class="fas fa-file-invoice-dollar" style="color: #388e3c;"></i></div>
                            <div class="widget-value" id="motor-bill">₹58.50</div>
                            <div class="widget-label">Est. Motor Bill (@ ₹13/unit)</div>
                        </div>
                    </div>

                    <div style="background: rgba(255,255,255,0.7); padding: 15px; border-radius: 12px; border: 1px solid rgba(0,0,0,0.05); display: flex; align-items: center; justify-content: space-between;">
                        <div style="text-align: center; padding-right: 20px; border-right: 1px solid rgba(0,0,0,0.1);">
                            <div style="font-size: 2.5rem; font-weight: 700; color: var(--primary); line-height: 1;" id="detail-temp">72°F</div>
                            <div style="font-size: 0.9rem; color: var(--text-muted); margin-top: 5px;">Feels like <span id="detail-feels">74°F</span></div>
                        </div>
                        <div style="flex: 1; padding-left: 20px; display: grid; grid-template-columns: 1fr 1fr; gap: 10px;">
                            <p style="margin: 0; font-size: 0.9rem;"><strong style="color: var(--text-main);">High/Low:</strong> <span id="detail-high-low">78° / 60°</span></p>
                            <p style="margin: 0; font-size: 0.9rem;"><strong style="color: var(--text-main);">UV Index:</strong> <span id="detail-uv">6 (Mod)</span></p>
                            <p style="margin: 0; font-size: 0.9rem;"><strong style="color: var(--text-main);">Dew Point:</strong> <span id="detail-dew">55°F</span></p>
                            <p style="margin: 0; font-size: 0.9rem;"><strong style="color: var(--text-main);">Visibility:</strong> 10 mi</p>
                        </div>
                    </div>
                </div>

                <div class="panel" id="alerts-panel">
                    <h2 class="panel-title"><i class="fas fa-bell" style="color: var(--warning); margin-right: 10px;"></i> Active Alerts</h2>
                    <ul class="alerts-list" id="alerts-list">
                        <!-- Alerts will be generated by JavaScript -->
                    </ul>
                </div>

                <div class="panel">
                    <h2 class="panel-title"><i class="fas fa-leaf" style="color: var(--success); margin-right: 10px;"></i> Crop Status</h2>
                    <div style="display: flex; margin-bottom: 20px; gap: 20px; flex-wrap: wrap;">
                        <div style="flex: 1; min-width: 200px;">
                            <img src="Corn image.jpg" alt="Corn field" class="crop-image" id="crop-status-img">
                        </div>
                        <div style="flex: 1.5; min-width: 250px;">
                            <h3 id="crop-status-title" style="color: var(--primary-dark); margin-bottom: 10px;">Corn - V6 Growth Stage</h3>
                            <p class="crop-info"><i class="fas fa-calendar-check" style="color: var(--success); width: 20px;"></i> <span id="crop-status-planted">Planted: March 25, 2025</span></p>
                            <p class="crop-info"><i class="fas fa-tractor" style="color: var(--warning); width: 20px;"></i> <span id="crop-status-harvest">Est. Harvest: September 10, 2025</span></p>
                            <p class="crop-info"><i class="fas fa-sun" style="color: var(--secondary); width: 20px;"></i> <span id="crop-status-gdd">GDD: 512</span></p>

                            <div style="margin-top: 15px; background: rgba(0,0,0,0.02); padding: 15px; border-radius: 12px;">
                                <div style="display: flex; justify-content: space-between; font-weight: 600; font-size: 0.9rem;">
                                    <span>Growth Progress</span>
                                    <span id="crop-status-progress-text" style="color: var(--success);">30%</span>
                                </div>
                                <div class="progress-container">
                                    <div class="progress-bar" id="crop-status-progress-bar" style="width: 30%"></div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin-top: 20px;">
                        <div style="text-align: center; background: rgba(255,255,255,0.5); padding: 15px; border-radius: 12px; border: 1px solid rgba(0,0,0,0.05);">
                            <div style="font-size: 0.85rem; color: var(--text-muted); text-transform: uppercase;">Soil Temp</div>
                            <div style="font-size: 1.5rem; font-weight: 700; color: var(--text-main); margin: 5px 0;" id="crop-soil-temp">62°F</div>
                            <span class="badge badge-optimal" id="crop-soil-temp-badge">Optimal</span>
                        </div>
                        <div style="text-align: center; background: rgba(255,255,255,0.5); padding: 15px; border-radius: 12px; border: 1px solid rgba(0,0,0,0.05);">
                            <div style="font-size: 0.85rem; color: var(--text-muted); text-transform: uppercase;">Soil Moisture</div>
                            <div style="font-size: 1.5rem; font-weight: 700; color: var(--text-main); margin: 5px 0;" id="crop-soil-moisture">28%</div>
                            <span class="badge badge-caution" id="crop-soil-moisture-badge">Moderate</span>
                        </div>
                        <div style="text-align: center; background: rgba(255,255,255,0.5); padding: 15px; border-radius: 12px; border: 1px solid rgba(0,0,0,0.05);">
                            <div style="font-size: 0.85rem; color: var(--text-muted); text-transform: uppercase;">Growth Rate</div>
                            <div style="font-size: 1.5rem; font-weight: 700; color: var(--text-main); margin: 5px 0;" id="crop-growth-rate">+2.1"/wk</div>
                            <span class="badge badge-optimal" id="crop-growth-rate-badge">Normal</span>
                        </div>
                    </div>
                </div>

                <div class="panel">
                    <h2 class="panel-title"><i class="far fa-calendar-alt" style="color: var(--primary); margin-right: 10px;"></i> Planting Windows</h2>
                    <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-top: 15px;" id="planting-windows-container">
                        <!-- Planting windows will be generated dynamically by JavaScript -->
                    </div>
                </div>

                <div class="panel">
                    <h2 class="panel-title"><i class="fas fa-cog" style="color: var(--text-muted); margin-right: 10px;"></i> Alert Settings</h2>
                    <div class="settings-group">
                        <span class="settings-label">Frost Alerts</span>
                        <label class="toggle-switch">
                            <input type="checkbox" id="frost-alerts" checked>
                            <span class="toggle-slider"></span>
                        </label>
                    </div>
                    <div class="settings-group">
                        <span class="settings-label">Drought Conditions</span>
                        <label class="toggle-switch">
                            <input type="checkbox" id="drought-alerts" checked>
                            <span class="toggle-slider"></span>
                        </label>
                    </div>
                    <div class="settings-group">
                        <span class="settings-label">SMS Notifications</span>
                        <label class="toggle-switch">
                            <input type="checkbox" id="sms-notifications" checked>
                            <span class="toggle-slider"></span>
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        window.onerror = function(message, source, lineno, colno, error) {
            alert("Javascript Error: " + message + " (Line " + lineno + ")");
            return false;
        };

        window.addEventListener('unhandledrejection', function(event) {
            alert("Async JS Error: " + event.reason);
        });

        document.addEventListener('DOMContentLoaded', function() {
            // CSRF Setup for fetch
            const csrfMeta = document.querySelector('meta[name="csrf-token"]');
            const csrfToken = csrfMeta ? csrfMeta.getAttribute('content') : '';

            // Set current date
            const currentDate = new Date();
            const currentDateEl = document.getElementById('current-date');
            if (currentDateEl) {
                currentDateEl.textContent = currentDate.toLocaleDateString('en-US', {
                    weekday: 'long',
                    year: 'numeric',
                    month: 'long',
                    day: 'numeric'
                });
            }

            // Generate alerts
            const alerts = [{
                    type: 'frost',
                    title: 'Overnight Frost Risk',
                    message: 'Temperatures expected to drop to 32°F overnight. Consider protecting sensitive crops.',
                    time: 'Today, 8:15 AM',
                    icon: '❄️'
                },
                {
                    type: 'drought',
                    title: 'Moderate Drought Alert',
                    message: 'Rainfall 35% below average for the season. Consider adjusting irrigation schedules.',
                    time: 'Yesterday, 3:42 PM',
                    icon: '☀️'
                },
                {
                    type: 'planting',
                    title: 'Optimal Corn Planting Window',
                    message: 'Soil temperature and moisture levels optimal for corn planting in the next 14 days.',
                    time: 'Yesterday, 9:20 AM',
                    icon: '🌱'
                }
            ];

            const alertsList = document.getElementById('alerts-list');

            alerts.forEach(alert => {
                const alertElement = document.createElement('li');
                alertElement.className = \`alert-item \${alert.type}-alert\`;

                alertElement.innerHTML = \`
                    <div class="alert-icon \${alert.type}-icon">\${alert.icon}</div>
                    <div class="alert-content">
                        <div class="alert-title">\${alert.title}</div>
                        <div class="alert-message">\${alert.message}</div>
                        <div class="alert-time"><i class="far fa-clock"></i> \${alert.time}</div>
                        <div class="alert-actions">
                            <button class="alert-button"><i class="fas fa-check"></i> Mark as Read</button>
                        </div>
                    </div>
                \`;

                alertsList.appendChild(alertElement);
            });

            // Handle mark as read buttons
            document.addEventListener('click', function (e) {
                if (e.target.closest('.alert-button')) {
                    const alertItem = e.target.closest('.alert-item');
                    alertItem.style.opacity = '0.4';
                    alertItem.style.transform = 'scale(0.98)';

                    const notificationBadge = document.querySelector('.notification-badge');
                    let count = parseInt(notificationBadge.textContent);
                    if (count > 0) notificationBadge.textContent = count - 1;
                }
            });

            // Update Dashboard Data Dynamics
            const updateDashboard = function() {
                const locationInput = document.getElementById('location').value;
                let fieldSizeStr = document.getElementById('field-size').value.replace(/[^0-9.]/g, '');
                let fieldSize = parseFloat(fieldSizeStr) || 120;
                const selectedCrop = document.getElementById('crop-type').value;
                const selectedSoil = document.getElementById('soil-type').value;

                // Update location and field size visually
                if (document.getElementById('display-location')) {
                    document.getElementById('display-location').textContent = locationInput;
                }
                if (document.getElementById('display-field-size')) {
                    document.getElementById('display-field-size').textContent = fieldSize + ' acres';
                }

                // DYNAMIC CALCULATIONS BASED ON FIELD SIZE
                // 1. Water Invested Today (Liters) = Field Size * 1250 (random multiplier)
                const waterInvested = Math.round(fieldSize * 1250);
                document.getElementById('water-invested').textContent = waterInvested.toLocaleString() + ' L';

                // 2. Motor Run Time (Hours) = Field Size / 15
                const motorHours = (fieldSize / 15).toFixed(1);
                document.getElementById('motor-runtime').textContent = motorHours + ' hrs';

                // 3. Est. Motor Bill = Hours * 5 kWh (pump power) * ₹13/unit
                const motorBill = (motorHours * 5 * 13).toFixed(2);
                document.getElementById('motor-bill').textContent = '₹' + parseFloat(motorBill).toLocaleString();

                // 4. Farmers on Field = Math.ceil(fieldSize / 20)
                const farmersCount = Math.ceil(fieldSize / 20) + Math.floor(Math.random() * 3);
                document.getElementById('farmer-count').textContent = farmersCount;

                // Crop Specific Info
                const cropData = {
                    corn: {
                        name: 'Corn', stage: 'V6 Growth Stage', planted: 'March 25, 2025', harvest: 'September 10, 2025', gdd: '512 GDD', progress: '30%', image: 'Corn image.jpg', temp: '68°F', tempStatus: 'Optimal', moist: '28%', moistStatus: 'Moderate', rate: '+2.1"/wk', rateStatus: 'Normal'
                    },
                    wheat: {
                        name: 'Wheat', stage: 'Tillering Stage', planted: 'November 10, 2024', harvest: 'June 25, 2025', gdd: '850 GDD', progress: '45%', image: 'Wheat image.jpg', temp: '55°F', tempStatus: 'Cool', moist: '22%', moistStatus: 'Low', rate: '+1.5"/wk', rateStatus: 'Slow'
                    },
                    soybean: {
                        name: 'Soybean', stage: 'Vegetative Emergence', planted: 'May 5, 2025', harvest: 'October 15, 2025', gdd: '120 GDD', progress: '15%', image: 'Soybean image.jpg', temp: '70°F', tempStatus: 'Optimal', moist: '45%', moistStatus: 'Good', rate: '+2.5"/wk', rateStatus: 'Fast'
                    },
                    rice: {
                        name: 'Rice', stage: 'Seedling Stage', planted: 'April 20, 2025', harvest: 'September 30, 2025', gdd: '300 GDD', progress: '20%', image: 'Rice image.jpg', temp: '75°F', tempStatus: 'Warm', moist: '85%', moistStatus: 'Optimal', rate: '+3.0"/wk', rateStatus: 'Fast'
                    },
                    alfalfa: {
                        name: 'Alfalfa', stage: 'Early Bud', planted: 'March 1, 2025', harvest: 'June 10, 2025', gdd: '600 GDD', progress: '60%', image: 'Alfalfa image.jpg', temp: '60°F', tempStatus: 'Optimal', moist: '30%', moistStatus: 'Moderate', rate: '+1.8"/wk', rateStatus: 'Normal'
                    },
                    tomatoes: {
                        name: 'Tomatoes', stage: 'Flowering', planted: 'April 10, 2025', harvest: 'August 15, 2025', gdd: '450 GDD', progress: '40%', image: 'Tomatoes image.jpg', temp: '72°F', tempStatus: 'Optimal', moist: '50%', moistStatus: 'Good', rate: '+2.2"/wk', rateStatus: 'Normal'
                    }
                };

                const data = cropData[selectedCrop] || cropData['corn'];

                document.getElementById('crop-status-title').textContent = data.name + ' - ' + data.stage;
                document.getElementById('crop-status-planted').innerHTML = 'Planted: ' + data.planted;
                document.getElementById('crop-status-harvest').innerHTML = 'Est. Harvest: ' + data.harvest;
                document.getElementById('crop-status-gdd').innerHTML = 'GDD: ' + data.gdd;

                document.getElementById('crop-status-progress-text').textContent = data.progress;
                document.getElementById('crop-status-progress-bar').style.width = data.progress;
                document.getElementById('crop-status-img').alt = data.name + ' field';
                document.getElementById('crop-status-img').src = data.image;

                let moistValue = parseInt(data.moist);
                if (selectedSoil === 'clay' || selectedSoil === 'clay-loam') moistValue = Math.min(100, moistValue + 15);
                else if (selectedSoil === 'sandy') moistValue = Math.max(0, moistValue - 15);
                else if (selectedSoil === 'silt') moistValue = Math.min(100, moistValue + 8);
                else if (selectedSoil === 'loam') moistValue = Math.min(100, moistValue + 5);
                
                let finalMoist = \`\${moistValue}%\`;
                let moistStatus = data.moistStatus;
                if (moistValue < 25) moistStatus = 'Low';
                else if (moistValue > 40 && moistValue < 70) moistStatus = 'Good';

                document.getElementById('crop-soil-temp').textContent = data.temp;
                document.getElementById('crop-soil-temp-badge').textContent = data.tempStatus;
                document.getElementById('crop-soil-temp-badge').className = data.tempStatus === 'Optimal' ? 'badge badge-optimal' : 'badge badge-caution';

                document.getElementById('crop-soil-moisture').textContent = finalMoist;
                document.getElementById('crop-soil-moisture-badge').textContent = moistStatus;
                document.getElementById('crop-soil-moisture-badge').className = moistStatus === 'Good' || moistStatus === 'Optimal' ? 'badge badge-optimal' : (moistStatus === 'Low' ? 'badge badge-warning' : 'badge badge-caution');

                document.getElementById('crop-growth-rate').textContent = data.rate;
                document.getElementById('crop-growth-rate-badge').textContent = data.rateStatus;
                document.getElementById('crop-growth-rate-badge').className = data.rateStatus === 'Fast' || data.rateStatus === 'Normal' ? 'badge badge-optimal' : 'badge badge-warning';
                
                // Update Planting Windows dynamically
                const plantingWindowsData = {
                    corn: { name: 'Corn', window: 'Mar 15 - Apr 30', status: 'In Progress', statusClass: 'badge-optimal', temp: '62°F (>55°F)', daysDesc: 'Days Left', days: '14', color: 'rgba(232, 245, 233, 0.5)', border: '#4caf50' },
                    wheat: { name: 'Winter Wheat', window: 'Oct 1 - Nov 15', status: 'Months Away', statusClass: 'badge-warning', temp: 'Off-season', daysDesc: 'Days Until', days: '168', color: 'rgba(255, 248, 225, 0.5)', border: '#ffb300' },
                    soybean: { name: 'Soybeans', window: 'May 1 - Jun 15', status: 'Coming Soon', statusClass: 'badge-caution', temp: '62°F (>60°F)', daysDesc: 'Days Until', days: '16', color: 'rgba(224, 247, 250, 0.5)', border: '#00acc1' },
                    rice: { name: 'Rice', window: 'Apr 1 - May 20', status: 'In Progress', statusClass: 'badge-optimal', temp: '65°F (>60°F)', daysDesc: 'Days Left', days: '35', color: 'rgba(232, 245, 233, 0.5)', border: '#4caf50' }
                };
                
                const pwContainer = document.getElementById('planting-windows-container');
                if (pwContainer) {
                    const pw = plantingWindowsData[selectedCrop] || plantingWindowsData['corn'];
                    const otherKeys = Object.keys(plantingWindowsData).filter(k => k !== selectedCrop).slice(0, 3);
                    
                    let html = \`
                        <div style="padding: 15px; border-radius: 12px; background-color: \${pw.color}; border-left: 4px solid \${pw.border};">
                            <h3 style="font-size: 1.1rem; margin-bottom: 5px;">\${pw.name} (Primary)</h3>
                            <p style="font-size: 0.9rem;"><strong>Window:</strong> \${pw.window}</p>
                            <p style="font-size: 0.9rem; margin: 5px 0;"><strong>Status:</strong> <span class="badge \${pw.statusClass}">\${pw.status}</span></p>
                            <p style="font-size: 0.9rem;"><strong>Soil Temp:</strong> \${pw.temp}</p>
                        </div>
                    \`;
                    
                    otherKeys.forEach(k => {
                        const opw = plantingWindowsData[k];
                        html += \`
                        <div style="padding: 15px; border-radius: 12px; background-color: \${opw.color}; border-left: 4px solid \${opw.border};">
                            <h3 style="font-size: 1.1rem; margin-bottom: 5px;">\${opw.name}</h3>
                            <p style="font-size: 0.9rem;"><strong>Window:</strong> \${opw.window}</p>
                            <p style="font-size: 0.9rem; margin: 5px 0;"><strong>Status:</strong> <span class="badge \${opw.statusClass}">\${opw.status}</span></p>
                            <p style="font-size: 0.9rem;"><strong>Soil Temp:</strong> \${opw.temp}</p>
                        </div>
                        \`;
                    });
                    
                    pwContainer.innerHTML = html;
                }
            };

            // Dynamic location weather generation
            const updateWeatherForLocation = function() {
                const baseTemp = Math.floor(Math.random() * 30) + 55;
                document.getElementById('current-temp').textContent = \`\${baseTemp}°F\`;
                document.getElementById('detail-temp').textContent = \`\${baseTemp}°F\`;
                document.getElementById('detail-feels').textContent = \`\${baseTemp + 2}°F\`;
                document.getElementById('detail-high-low').textContent = \`\${baseTemp + 6}° / \${baseTemp - 8}°\`;
                
                document.getElementById('current-humidity').textContent = \`\${Math.floor(Math.random() * 40) + 30}%\`;
                document.getElementById('current-wind').textContent = \`\${Math.floor(Math.random() * 15) + 3} mph\`;
                
                // Update 5-day forecast
                const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
                const today = new Date().getDay();
                const forecastDays = Array.from({length: 5}, (_, i) => days[(today + i) % 7]);
                const weatherIcons = ['☀️', '⛅', '☁️', '🌧️', '⛈️'];
                const forecastContainer = document.getElementById('forecast-container');
                forecastContainer.innerHTML = '';
                
                forecastDays.forEach((day) => {
                    const icon = weatherIcons[Math.floor(Math.random() * weatherIcons.length)];
                    const temp = Math.floor(Math.random() * 30) + 55;
                    const dayElement = document.createElement('div');
                    dayElement.className = 'forecast-day';
                    dayElement.innerHTML = \`
                        <div class="day-name">\${day}</div>
                        <div style="font-size: 24px; margin: 5px 0;">\${icon}</div>
                        <div class="day-temp">\${temp}°</div>
                    \`;
                    forecastContainer.appendChild(dayElement);
                });
            };

            document.getElementById('location').addEventListener('change', updateWeatherForLocation);

            // Listeners for dynamic updates
            document.getElementById('crop-type').addEventListener('change', updateDashboard);
            document.getElementById('soil-type').addEventListener('change', updateDashboard);
            document.getElementById('location').addEventListener('input', updateDashboard);
            document.getElementById('field-size').addEventListener('input', updateDashboard);

            // AJAX TO-DO LIST FUNCTIONALITY
            const todoInput = document.getElementById('new-todo-input');
            const addTodoBtn = document.getElementById('add-todo-btn');
            const todoList = document.getElementById('todo-list');

            addTodoBtn.addEventListener('click', async function() {
                const task = todoInput.value.trim();
                if (!task) return;

                addTodoBtn.disabled = true;
                addTodoBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i>';

                try {
                    const response = await fetch('{{ route("alert.todo.store") }}', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'Accept': 'application/json',
                            'X-Requested-With': 'XMLHttpRequest',
                            'X-CSRF-TOKEN': csrfToken
                        },
                        body: JSON.stringify({ task: task })
                    });

                    if (response.ok) {
                        const data = await response.json();
                        if (data.success) {
                            // Clear "No tasks" message if it exists
                            if (todoList.children.length === 1 && todoList.children[0].tagName === 'LI' && !todoList.children[0].classList.contains('todo-item')) {
                                todoList.innerHTML = '';
                            }

                            // Append new task
                            const li = document.createElement('li');
                            li.className = 'todo-item';
                            li.setAttribute('data-id', data.todo.id);
                            li.innerHTML = ` <
                    input type = "checkbox"
                class = "todo-checkbox" >
                <
                span class = "todo-text" > $ {
                    data.todo.task
                } < /span>
                `;
                            todoList.prepend(li);
                            todoInput.value = '';
                        }
                    } else {
                        if (response.status === 419 || response.status === 401) {
                            alert("Session expired. Please refresh the page or log in again.");
                        } else {
                            const errMessage = await response.text();
                            alert("Error adding task: " + response.status + "\n" + errMessage);
                            console.error(errMessage);
                        }
                    }
                } catch (error) {
                    console.error("Error adding todo:", error);
                    alert("Network error adding task.");
                } finally {
                    addTodoBtn.disabled = false;
                    addTodoBtn.innerHTML = '<i class="fas fa-plus"></i>';
                }
            });

            // Toggle checkbox event delegation
            todoList.addEventListener('change', async function(e) {
                if (e.target.classList.contains('todo-checkbox')) {
                    const li = e.target.closest('.todo-item');
                    const id = li.getAttribute('data-id');
                    
                    // Optimistic update
                    if (e.target.checked) {
                        li.classList.add('completed');
                    } else {
                        li.classList.remove('completed');
                    }

                    try {
                        const response = await fetch(` / alert / todo / $ {
                    id
                }
                /toggle`, {
                method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Accept': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest',
                        'X-CSRF-TOKEN': csrfToken
                    }
            });
            if (!response.ok) {
                if (response.status === 419 || response.status === 401) {
                    alert("Session expired. Please refresh the page or log in again.");
                } else {
                    alert("Error toggling task: " + response.status + " " + response.statusText);
                }
                e.target.checked = !e.target.checked;
                li.classList.toggle('completed');
            }
        } catch (error) {
            console.error("Error toggling todo:", error);
            // Revert on error
            e.target.checked = !e.target.checked;
            li.classList.toggle('completed');
        }
        }
        });

        // Handle Profile Update Button click
        const profileBtn = document.getElementById('update-profile-btn');
        profileBtn.addEventListener('click', async function() {
            const btn = this;
            const originalText = btn.innerHTML;
            btn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Saving...';
            btn.disabled = true;

            updateDashboard();

            const locationInput = document.getElementById('location').value;
            const fieldSizeInput = document.getElementById('field-size').value;
            const cropName = document.getElementById('crop-type').value;
            const soilName = document.getElementById('soil-type').value;

            try {
                const response = await fetch('{{ route("alert.profile") }}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Accept': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest',
                        'X-CSRF-TOKEN': csrfToken
                    },
                    body: JSON.stringify({
                        location: locationInput,
                        field_size: fieldSizeInput,
                        primary_crop: cropName,
                        soil_type: soilName
                    })
                });

                if (response.ok) {
                    btn.style.background = 'linear-gradient(135deg, #2e7d32, #4caf50)';
                    btn.innerHTML = '<i class="fas fa-check"></i> Saved!';
                    setTimeout(() => {
                        btn.style.background = '';
                        btn.innerHTML = originalText;
                        btn.disabled = false;
                    }, 2000);
                } else {
                    if (response.status === 419 || response.status === 401) {
                        alert("Session expired. Please refresh the page or log in again.");
                    } else {
                        const errMessage = await response.text();
                        alert("Failed to update profile. Status: " + response.status + "\n" + errMessage);
                        console.error(errMessage);
                    }
                    btn.innerHTML = originalText;
                    btn.disabled = false;
                }
            } catch (error) {
                console.error('Error:', error);
                alert("Network error updating profile.");
                btn.innerHTML = originalText;
                btn.disabled = false;
            }
        });

        // Run initial setup
        updateWeatherForLocation();
        updateDashboard();
        });
    </script>
</body>

</html>